services:
  - type: web
    name: documed-by-hvirfill
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: ""
      - key: GROQ_PROVIDER
        value: auto
